-- AlterTable
ALTER TABLE `resource` ADD COLUMN `category` ENUM('ANXIETY', 'FOCUS', 'SLEEP', 'MINDFULNESS', 'GENERAL') NOT NULL DEFAULT 'GENERAL',
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `duration` VARCHAR(191) NULL,
    ADD COLUMN `isFeatured` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `description` TEXT NULL;
